# xView Dataset Class Mapping
# Complete mapping of xView category IDs to class names
# Source: https://challenge.xviewdataset.org/

classes:
  # Vehicles
  11: "Fixed-Wing Aircraft"
  12: "Small Vehicle"
  13: "Large Vehicle"
  15: "Truck"
  17: "Cargo Truck"
  18: "Truck Tractor"
  19: "Trailer"
  20: "Truck w/Box"
  21: "Passenger Vehicle"
  22: "Mobile Home"
  23: "Truck w/Flatbed"
  24: "Truck w/Liquid"
  25: "Crane Truck"
  26: "Railway Vehicle"
  27: "Tram"
  28: "Container"
  29: "Reach Stacker"
  30: "Straddle Carrier"
  31: "Mobile Crane"
  32: "Dump Truck"
  33: "Haul Truck"
  34: "Scraper/Tractor"
  35: "Front loader/Bulldozer"
  36: "Yacht"
  37: "Sailboat"
  38: "Fishing Vessel"
  39: "Tugboat"
  40: "Barge"
  41: "Ferry"
  42: "Container Ship"
  43: "Oil Tanker"
  44: "Engineering Vehicle"
  45: "Tower Crane"
  46: "Container Crane"
  47: "Reach Stacker"
  48: "Straddle Carrier"
  49: "Mobile Crane"

  # Buildings & Infrastructure
  50: "Hut/Tent"
  51: "Shed"
  52: "Building"
  53: "Aircraft Hangar"
  54: "Damaged Building"
  55: "Facility"
  56: "Vehicle Lot"
  57: "Helipad"
  58: "Storage Tank"
  59: "Shipping Container"
  60: "Shipping Container Lot"
  61: "Pylon"
  62: "Tower"

  # Other
  63: "Excavator"
  64: "Maritime Vessel"
  65: "Vehicle"
  66: "Engineering Vehicle"
  67: "Aircraft"
  68: "Building"
  69: "Infrastructure"
  70: "Person"

# Simplified class set for focused training (most common classes)
simplified_classes:
  11: "Fixed-Wing Aircraft"
  12: "Small Vehicle"
  13: "Large Vehicle"
  15: "Truck"
  21: "Passenger Vehicle"
  37: "Ship"
  52: "Building"
  57: "Helipad"
  58: "Storage Tank"
  59: "Shipping Container"
